<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'BricksAssetTest\Bootstrap'                     => __DIR__ . '/Bootstrap.php',
  'BricksAssetTest\AssetService\AssetServiceTest' => __DIR__ . '/BricksAssetTest/AssetService/AssetServiceTest.php',
  'BricksAssetTest\Mock\Adapter'                  => __DIR__ . '/BricksAssetTest/Mock/Adapter.php',
  'BricksAssetTest\Mock\ClassLoader'              => __DIR__ . '/BricksAssetTest/Mock/ClassLoader.php',
  'BricksAssetTest\Mock\LessStrategy'             => __DIR__ . '/BricksAssetTest/Mock/LessStrategy.php',
  'BricksAssetTest\Mock\MinifyCssStrategy'        => __DIR__ . '/BricksAssetTest/Mock/MinifyCssStrategy.php',
  'BricksAssetTest\Mock\MinifyJsStrategy'         => __DIR__ . '/BricksAssetTest/Mock/MinifyJsStrategy.php',
  'BricksAssetTest\Mock\PublishStrategy'          => __DIR__ . '/BricksAssetTest/Mock/PublishStrategy.php',
  'BricksAssetTest\Mock\RemoveStrategy'           => __DIR__ . '/BricksAssetTest/Mock/RemoveStrategy.php',
  'BricksAssetTest\Mock\ScssStrategy'             => __DIR__ . '/BricksAssetTest/Mock/ScssStrategy.php',
  'BricksAssetTest\View\Helper\HeadLinkTest'      => __DIR__ . '/BricksAssetTest/View/Helper/HeadLinkTest.php',
);
