<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'BricksAsset\Module'                                              => __DIR__ . '/Module.php',
  'Bricks\AssetService\AssetService'                                => __DIR__ . '/src/Bricks/AssetService/AssetService.php',
  'Bricks\AssetService\LessAdapter\LessAdapterInterface'            => __DIR__ . '/src/Bricks/AssetService/LessAdapter/LessAdapterInterface.php',
  'Bricks\AssetService\LessAdapter\NeilimeLessphpAdapter'           => __DIR__ . '/src/Bricks/AssetService/LessAdapter/NeilimeLessphpAdapter.php',
  'Bricks\AssetService\MinifyAdapter\MinifyAdapterInterface'        => __DIR__ . '/src/Bricks/AssetService/MinifyAdapter/MinifyAdapterInterface.php',
  'Bricks\AssetService\MinifyAdapter\MrclayMinifyAdapter'           => __DIR__ . '/src/Bricks/AssetService/MinifyAdapter/MrclayMinifyAdapter.php',
  'Bricks\AssetService\PublishAdapter\CopyAdapter'                  => __DIR__ . '/src/Bricks/AssetService/PublishAdapter/CopyAdapter.php',
  'Bricks\AssetService\PublishAdapter\PublishAdapterInterface'      => __DIR__ . '/src/Bricks/AssetService/PublishAdapter/PublishAdapterInterface.php',
  'Bricks\AssetService\ScssAdapter\LeafoScssphpAdapter'             => __DIR__ . '/src/Bricks/AssetService/ScssAdapter/LeafoScssphpAdapter.php',
  'Bricks\AssetService\ScssAdapter\ScssAdapterInterface'            => __DIR__ . '/src/Bricks/AssetService/ScssAdapter/ScssAdapterInterface.php',
  'Bricks\View\Helper\HeadLink'                                     => __DIR__ . '/src/Bricks/View/Helper/HeadLink.php',
  'Bricks\View\Helper\HeadLinkDelegator'                            => __DIR__ . '/src/Bricks/View/Helper/HeadLinkDelegator.php',
  'Bricks\View\Helper\HeadScript'                                   => __DIR__ . '/src/Bricks/View/Helper/HeadScript.php',
  'Bricks\View\Helper\HeadScriptDelegator'                          => __DIR__ . '/src/Bricks/View/Helper/HeadScriptDelegator.php',
  'BricksAsset\Controller\AssetController'                          => __DIR__ . '/src/BricksAsset/Controller/AssetController.php',
  'BricksAsset\Controller\MenuController'                           => __DIR__ . '/src/BricksAsset/Controller/MenuController.php',
  'BricksAssetTest\Bootstrap'                                       => __DIR__ . '/test/Bootstrap.php',
  'BricksAssetTest\AssetService\AssetServiceTest'                   => __DIR__ . '/test/BricksAssetTest/AssetService/AssetServiceTest.php',
  'BricksAssetTest\Mocking\AssetService\PublishAdapter\MockAdapter' => __DIR__ . '/test/BricksAssetTest/Mocking/AssetService/PublishAdapter/MockAdapter.php',
  'BricksAssetTest\View\Helper\HeadLinkTest'                        => __DIR__ . '/test/BricksAssetTest/View/Helper/HeadLinkTest.php',
);
