<form name="publish" action="<?php echo $this->Url('bricksasset-publish-do'); ?>" method="post" class="grid_12 grid_12_pad10 box">
	<h1>Öffentliche Dateien schreiben</h1>
	<p>
		Bevor die Resourcen-Dateien aus den Modulen verwendet werden können, müssen
		diese über den Browser erreichbar gemacht werden.<br />
		<br />
		<input type="submit" name="_submit" value="Assets schreiben" />
	</p>
</form>