<div class="container bricks-assets-publish">
	<div class="row row-fit-height">
		<div class="col-md-7 col-md-full-height">
			<div class="box">
				<h1><div class="pad-5"><?php echo $this->translate('Write public files'); ?></div></h1>
				<div class="pad-10">			
					<form name="publish" action="<?php echo $this->Url('bricks.asset.publish.do'); ?>" method="post">									
						<?php echo $this->Form($this->publishForm); ?>	
					</form>
				</div>	
			</div>
		</div>
		<div class="col-md-4 col-md-full-height">
			<div class="box pad-10">
				<p>
					<?php echo $this->translate('Before you can use the public files of a module they have to be published in a public reachable directory.'); ?>				
				</p>
				<p>
					<?php echo $this->translate('To use the published resources you\'ve to begin with the modules name followed by the path as it is stored in your modules public dir.'); ?>
				</p>
				<pre>&lt;?php 
	$this-&gt;HeadLink()-&gt;appendStylesheet('MyModuleName/path/to/css.css');
?&gt;</pre>
			</div>
		</div>
	</div>
</div>